- name: Установка Patroni
  apt:
    name: patroni
    state: present

- name: Настройка Patroni
  template:
    src: patroni.yml.j2
    dest: /etc/patroni/patroni.yml
    owner: postgres
    group: postgres
    mode: '0644'

- name: Запуск и включение Patroni
  service:
    name: patroni
    state: started
    enabled: yes