all:
  hosts:
    node1:
      ansible_host: 10.3.26.105
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      #ansible_python_interpreter: /usr/bin/python3
    node2:
        ansible_host: 10.3.26.101
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        #ansible_python_interpreter: /usr/bin/python3
    node3:
        ansible_host: 10.3.26.101
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        #ansible_python_interpreter: /usr/bin/python3
      


