- name: Этап 1
  hosts: oracle_vm
  become: yes
  roles:
    - postgre/install_postgresql
    - postgre/configure_postgresql
    - packages
    - users/configure_sudo
    - users/create_usres
    - volume/mount_filesystem
    - volume/setup_lvm