- name: Устанавливаем PostgreSQL 15
  dnf:
    name: postgresql{{ postgresql_version }}-server
    state: present

- name: Инициализируем кластер PostgreSQL
  command: /usr/pgsql-{{ postgresql_version }}/bin/initdb -D /var/lib/pgsql/{{ postgresql_version }}/data --auth=md5 --auth-local=peer --auth-host=md5
  args:
    creates: /var/lib/pgsql/{{ postgresql_version }}/data/PG_VERSION

- name: Включаем контрольные суммы в конфигурации PostgreSQL
  lineinfile:
    path: /var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
    regexp: '^#?checkpoint_completion_target\s*='
    line: "checkpoint_completion_target = 0.5"
    state: present

- name: Запускаем и включаем службу PostgreSQL
  systemd:
    name: postgresql-{{ postgresql_version }}
    enabled: yes
    state: started
