---
# roles/postgresql/tasks/main.yml

- name: Install PostgreSQL 13 from Debian repos
  apt:
    name:
      - postgresql
      - postgresql-client
      - postgresql-contrib
      - python3-psycopg2
      - libpq-dev
    state: present
    update_cache: yes
  tags: postgresql

- name: Stop and disable default PostgreSQL service
  systemd:
    name: postgresql
    state: stopped
    enabled: no
  tags: postgresql

- name: Create PostgreSQL directory structure
  block:
    - name: Ensure data directory exists
      file:
        path: /var/lib/postgresql/13/main
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Ensure WAL archive directory exists
      file:
        path: /var/lib/postgresql/wal_archive
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Ensure run directory exists
      file:
        path: /var/run/postgresql
        state: directory
        owner: postgres
        group: postgres
        mode: '0775'
  tags: config

- name: Clean default configuration
  file:
    path: /etc/postgresql/13/main
    state: absent
  tags: config