---
- name: Установка HAProxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Копирование конфигурации HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'

- name: Включение и перезапуск HAProxy
  systemd:
    name: haproxy
    state: restarted
    enabled: yes