---
- name: Setup PostgreSQL physical backup
  hosts: oracle_vm
  become: yes
  vars:
    backup_dir: /var/tmp
    pg_data_dir: /var/lib/pgsql/data
  tasks:
    - name: Ensure backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Stop PostgreSQL service
      service:
        name: postgresql
        state: stopped

    - name: Create physical backup of PostgreSQL data directory
      command: rsync -av --delete "{{ pg_data_dir }}/" "{{ backup_dir }}/"
      become_user: postgres

    - name: Start PostgreSQL service
      service:
        name: postgresql
        state: started
