---
- name: Install required system packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - virtualenv
    state: latest
    update_cache: true

- name: Remove incorrect Docker repository file (if exists)
  file:
    path: /etc/apt/sources.list.d/docker-ce.list
    state: absent

- name: Add Docker GPG key (modern method)
  shell: |
    curl -fsSL https://download.docker.com/linux/{{ ansible_os_family | lower }}/gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg
  args:
    creates: /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg

- name: Add Docker Repository with correct architecture
  apt_repository:
    repo: >
      deb [arch={{ 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }}
           signed-by=/etc/apt/trusted.gpg.d/docker-archive-keyring.gpg]
      https://download.docker.com/linux/{{ ansible_os_family | lower }}
      {{ ansible_distribution_release }} stable
    state: present
    filename: docker-ce
    update_cache: yes

- name: Update apt and install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: true

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add users to the Docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"