- name: Уменьшаем файловую систему на LV
  command: resize2fs /dev/ol/root 10G
  when: "'/dev/ol/root' in ansible_mounts and ansible_mounts['/dev/ol/root'].size_total > 10G"

- name: Уменьшаем размер LV
  lvol:
    vg: ol
    lv: root
    size: 10G
    state: present
    resizefs: false

- name: Создаем новый логический том (LV) в VG ol
  lvol:
    vg: ol
    lv: lv_pgsql
    size: 100%FREE
    state: present