- name: Создание директории для данных PostgreSQL
  file:
    path: "{{ postgres_data_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Инициализация PostgreSQL с контрольными суммами
  shell: "postgresql-setup initdb --locale=en_US.UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8 --checksums"
  args:
    creates: "{{ postgres_data_dir }}/PG_VERSION"

- name: Настройка postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: "{{ postgres_data_dir }}/postgresql.conf"
    owner: postgres
    group: postgres
    mode: '0600'
  notify: restart postgres

- name: Настройка pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgres_data_dir }}/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: '0600'
  notify: restart postgres

- name: Запуск и включение PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes
