- name: Настраиваем удаленный доступ в postgresql.conf
  lineinfile:
    path: /var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
    regexp: '^#?listen_addresses\s*='
    line: "listen_addresses = '*'"
    state: present

- name: Настраиваем pg_hba.conf для удаленного доступа
  blockinfile:
    path: /var/lib/pgsql/{{ postgresql_version }}/data/pg_hba.conf
    block: |
      host    all             all             0.0.0.0/0               md5
      host    all             all             ::1/128                 md5
    state: present

- name: Создаем пользователя PostgreSQL
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: SUPERUSER
  become_user: postgres

- name: Создаем базу данных из дампа
  postgresql_db:
    name: "{{ db_name }}"
    state: restore
    target: "{{ dump_file_path }}"
  become_user: postgres

- name: Предоставляем полный доступ пользователю к базе данных
  postgresql_privs:
    db: "{{ db_name }}"
    roles: "{{ db_user }}"
    type: database
    privs: ALL
  become_user: postgres
