- name: Удаление старой директории данных PostgreSQL
  file:
    path: "{{ postgres_data_dir }}"
    state: absent

- name: Создание директории для данных PostgreSQL
  file:
    path: "{{ postgres_data_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Инициализация PostgreSQL с контрольными суммами
  become: yes
  become_user: postgres
  shell: "initdb --locale=en_US.UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8 --data-checksums -D {{ postgres_data_dir }}"
  args:
    creates: "{{ postgres_data_dir }}/PG_VERSION"

- name: Настройка unix_socket_directories в postgresql.conf
  lineinfile:
    path: "{{ postgres_data_dir }}/postgresql.conf"
    regexp: '^#?unix_socket_directories'
    line: "unix_socket_directories = '/var/run/postgresql'"
    state: present
  notify: restart postgres

- name: Настройка listen_addresses в postgresql.conf
  lineinfile:
    path: "{{ postgres_data_dir }}/postgresql.conf"
    regexp: '^listen_addresses ='
    line: "listen_addresses = '*'"
    state: present
  notify: restart postgres

- name: Настройка pg_hba.conf
  template:
    src: postgre/configure_postgresql/templates/pg_hba.conf.j2  # Убедитесь, что путь указан правильно
    dest: "{{ postgres_data_dir }}/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: '0600'
  notify: restart postgres

- name: Запуск и включение PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes
