- name: Restart Patroni
  systemd:
    name: patroni
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable Patroni
  systemd:
    name: patroni
    enabled: yes